WONTFIX: Cannot export to PDF, switch to SVG instead
java.lang.ClassNotFoundException: org.apache.batik.apps.rasterizer.SVGConverter
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:421)
    at java.base/java.lang.Class.forName(Class.java:412)
    at net.sourceforge.plantuml.pdf.PdfConverter.convert(Unknown Source)
    ...